language: c
compiler:
  - gcc
  - clang
script: make && make test && ./sslsplit -V
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libssl-dev libevent-dev check
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
