language: c
compiler:
  - gcc
  - clang
# make test omitted because of missing libcheck on Ubuntu
script: make config && make
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libssl-dev libevent-dev
